// ─── Sports data and image utilities ─────────────────────────────────────────

export const sports = [
  {
    id: 'bodybuilding',
    name: 'Bodybuilding',
    description: 'Classic physique and open bodybuilding divisions under pro show lighting.',
    requiresPayment: false,
    prize: '₹5,00,000+ across divisions',
    date: 'Day 2 – Saturday',
    time: '4:00 PM – 9:00 PM',
    rules: [
      'Open & novice divisions by weight and height classes.',
      'Standard mandatory poses plus individual routines.',
      'Tanning, trunks, and posing music to follow event guidelines.',
    ],
    intensity: 'Stage',
  },
  {
    id: 'natural-bodybuilding',
    name: 'Natural Bodybuilding',
    description: 'Drug-tested physique competition focused on symmetry, conditioning, and proportion.',
    requiresPayment: false,
    prize: '₹3,00,000+ across tested divisions',
    date: 'Day 2 – Saturday',
    time: '10:00 AM – 3:00 PM',
    rules: [
      'Mandatory WADA-compliant testing protocol.',
      'Athletes must sign anti-doping declaration.',
      'Weight and height classes with symmetry-based judging.',
    ],
    intensity: 'Stage',
  },
  {
    id: 'powerlifting',
    name: 'Powerlifting',
    description: 'Squat, bench, and deadlift meet with calibrated plates and ranked judging.',
    requiresPayment: false,
    prize: '₹2,50,000+ best lifter & category awards',
    date: 'Day 1 – Friday',
    time: '10:00 AM – 6:00 PM',
    rules: [
      'IPF-style commands for all three lifts.',
      'Weigh-ins 2 hours before flight start.',
      'Equipment must meet federation regulations.',
    ],
    intensity: 'Strength',
  },
  {
    id: 'arm-wrestling',
    name: 'Arm Wrestling',
    description: 'Explosive table battles for right and left arms across multiple weight classes.',
    requiresPayment: false,
    prize: '₹1,50,000+ plus custom champion belts',
    date: 'Day 1 – Friday',
    time: '6:00 PM – 9:00 PM',
    rules: [
      'Athletes compete by right & left arm separately.',
      'Grip, ready, and go commands from referees.',
      'Elbow fouls and slips follow standard federation rules.',
    ],
    intensity: 'Strength',
  },
  {
    id: 'athrox',
    name: 'Athrox',
    description: 'Hybrid functional fitness championship combining strength, conditioning, and skills.',
    requiresPayment: true,
    prize: '₹6,00,000+ plus sponsor gear & endorsements',
    date: 'Day 3 – Sunday',
    time: '9:00 AM – 5:00 PM',
    rules: [
      'Multiple workouts of the day (WODs) released in advance.',
      'Movement standards briefing is mandatory.',
      'Scaled and RX divisions by gender and age.',
    ],
    intensity: 'Hybrid',
  },
  {
    id: 'strongman',
    name: 'Strongman',
    description: 'Brutal strongman arena featuring yoke carries, log press, and atlas stones.',
    requiresPayment: false,
    prize: '₹4,00,000+ for overall and event winners',
    date: 'Day 3 – Sunday',
    time: '11:00 AM – 7:00 PM',
    rules: [
      'Events announced with weight categories per division.',
      'Grip aids allowed as per event guidelines.',
      'Time caps enforced for each event.',
    ],
    intensity: 'Strength',
  },
  {
    id: 'marathon',
    name: 'Marathon',
    description: 'Urban route endurance run with electronic timing and epic expo start/finish.',
    requiresPayment: true,
    prize: '₹7,00,000+ overall & age-group prizes',
    date: 'Day 1 – Friday (Early Start)',
    time: '6:00 AM – 11:00 AM',
    rules: [
      'Timed distance with official timing chips.',
      'Hydration and aid stations throughout course.',
      'Medical clearance recommended for all runners.',
    ],
    intensity: 'Endurance',
  },
  {
    id: 'boxing',
    name: 'Boxing',
    description: 'Amateur and semi-pro bouts in a pro-built ring with full production.',
    requiresPayment: false,
    prize: '₹2,00,000+ plus performance bonuses',
    date: 'Day 2 – Saturday',
    time: '6:00 PM – 10:00 PM',
    rules: [
      'Age and weight-matched brackets.',
      'Mandatory medical checks and protective gear.',
      'Bouts officiated by licensed referees.',
    ],
    intensity: 'Combat',
  },
  {
    id: 'kickboxing',
    name: 'Kickboxing (MMA)',
    description: 'High-intensity striking and mixed martial arts showcases under safe rulesets.',
    requiresPayment: false,
    prize: '₹2,50,000+ across divisions',
    date: 'Day 3 – Sunday',
    time: '5:00 PM – 10:00 PM',
    rules: [
      'Bout rules and allowed techniques defined per category.',
      'Mandatory gloves, shin guards, and mouthguards.',
      'Doctor present cageside/ringside at all times.',
    ],
    intensity: 'Combat',
  },
  {
    id: 'fashion-show',
    name: 'Fashion Show',
    description: 'High-energy stage show featuring athleisure, physique, and brand runway walks.',
    requiresPayment: false,
    prize: 'Brand collaborations & feature coverage',
    date: 'Day 2 – Saturday',
    time: '8:00 PM – 10:00 PM',
    rules: [
      'Brand-approved wardrobe for each segment.',
      'Sequence and choreography rehearsals mandatory.',
      'Professional backstage timings to be followed strictly.',
    ],
    intensity: 'Stage',
  },
  {
    id: 'award-function',
    name: 'Award Function',
    description: 'Premium award ceremony celebrating winners, coaches, and industry leaders.',
    requiresPayment: false,
    prize: 'Trophies, medals, and recognition awards',
    date: 'Day 3 – Sunday',
    time: '8:00 PM – 10:00 PM',
    rules: [
      'Podium protocol and stage timings followed strictly.',
      'Athletes must be in event-appropriate attire.',
      'Media interviews and photo ops coordinated on site.',
    ],
    intensity: 'Stage',
  },
  {
    id: 'cycling',
    name: 'Cycling',
    description: 'High-speed criterium and endurance cycling events on a closed circuit.',
    requiresPayment: false,
    prize: '₹3,00,000+ across categories',
    date: 'Day 1 – Friday',
    time: '2:00 PM – 6:00 PM',
    rules: [
      'Helmets and safety gear compulsory.',
      'Timed laps with clear category splits.',
      'Drafting and team tactics allowed within rules.',
    ],
    intensity: 'Endurance',
  },
];

export const sportImageMap = {
  bodybuilding: '3837781/pexels-photo-3837781.jpeg',
  'natural-bodybuilding': '5327533/pexels-photo-5327533.jpeg',
  powerlifting: '841130/pexels-photo-841130.jpeg',
  'arm-wrestling': '4761785/pexels-photo-4761785.jpeg',
  athrox: '1552103/pexels-photo-1552103.jpeg',
  strongman: '1552103/pexels-photo-1552103.jpeg',
  marathon: '2402777/pexels-photo-2402777.jpeg',
  boxing: '4761660/pexels-photo-4761660.jpeg',
  kickboxing: '4761790/pexels-photo-4761790.jpeg',
  'fashion-show': '7671166/pexels-photo-7671166.jpeg',
  'award-function': '2384666/pexels-photo-2384666.jpeg',
  cycling: '276517/pexels-photo-276517.jpeg',
};

export function getSportImage(id) {
  const base = 'https://images.pexels.com/photos/';
  const path = sportImageMap[id] || '3837781/pexels-photo-3837781.jpeg';
  return `${base}${path}?auto=compress&w=1200`;
}
